---
- name: deploy zookeeper
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ release }}"
    exposed_ports:
      - "{{ exposed_ports }}"
    networks:
      - name: "edi_default"
    state: started
    restart: yes