---
- name: deploy kibana
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ release }}"
    ports:
      - "{{ ports }}"
    networks:
      - name: "{{ networks }}"
    state: started
    restart: yes